### Add book
POST http://localhost:4000/addBook
Content-Type: application/json

{
  "title": "Buku 4",
  "author": "Penulis 4"
}

### Get book
GET http://localhost:4000/getBooks

### Update book
PUT http://localhost:4000/editBook/1
Content-Type: application/json

{
  "title": "Buku 4.1",
  "author": "Penulis 4"
}

### Delete book based on index
DELETE http://localhost:4000/deleteBook/2