### Add book
POST http://localhost:4000/addBook
Content-Type: application/json

{
  "title": "Someone You Loved",
  "writer": "Lewis Capaldi",
  "published": "09 April 2019"
}

### Get book
GET http://localhost:4000/getBooks

### Update book
PUT http://localhost:4000/editBook/2
Content-Type: application/json

{
  "title": "You And I",
  "writer": "One Direction"
}

### Delete book based on index
DELETE http://localhost:4000/deleteBook/1 